---
# Copyright (c) 2019,2020 Fred Morris Tacoma WA USA m3047-pangolin-g3n@m3047.net
#
# This file is part of Pangolin
#
# Pangolin is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Pangolin is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Pangolin.  If not, see <http://www.gnu.org/licenses/>.
- name: Copy error document
  template:
    src: error.html.j2
    dest: "{{ os_vars[os].apache_docroot }}/error.html"
  become: yes
- name: Copy apache config
  copy:
    src: error-document.conf
    dest: /etc/apache2/sites-enabled/error-document.conf
  become: yes
