---
# Copyright (c) 2019 Fred Morris Tacoma WA USA m3047-pangolin-g3n@m3047.net
#
# This file is part of Pangolin
#
# Pangolin is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Pangolin is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Pangolin.  If not, see <http://www.gnu.org/licenses/>.
- name: Install Apache
  package:
    name: "{{ os_vars[os].apache }}"
    state: present
  become: yes
- name: Disable Apache
  systemd:
    name: "{{ os_vars[os].apache }}"
    state: stopped
    enabled: no
  become: yes
- name: Tabula rasa
  file:
    path: "{{ os_vars[os].apache_sites }}"
    state: absent
  become: yes
- file:
    path: "{{ os_vars[os].apache_sites }}"
    state: directory
    mode: "u=rwx,go=rx"
  become: yes
- name: Create appropriate doc path
  file:
    path: "{{ os_vars[os].apache_docroot }}/htdocs"
    state: directory
  become: yes
- name: Delete any default index.html doc
  file:
    path: "{{ os_vars[os].apache_docroot }}/index.html"
    state: absent
  become: yes
- name: Set up config and directory structure
  include_tasks: basic_setup.yml
- name: Add global error document
  include_tasks: error_document.yml
- name: Fix permissions on html doc tree
  file:
    path: "{{ os_vars[os].apache_docroot }}"
    state: directory
    owner: "{{ os_vars[os].apache_user }}"
    group: "{{ os_vars[os].apache_group }}"
    recurse: yes
  become: yes
  