---
# Copyright (c) 2019 Fred Morris Tacoma WA USA m3047-pangolin-g3n@m3047.net
#
# This file is part of Pangolin
#
# Pangolin is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Pangolin is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Pangolin.  If not, see <http://www.gnu.org/licenses/>.
#
# Unprivileged Users and World Readable Files
# -------------------------------------------
# The etherpad_server role attempts to install etherpad under a new,
# unprivileged user etherpad. This will probably require setting
#
#        allow_world_readable_tmpfiles = True
#
# in ansible.cfg.
#
# Locatons and Versions of NodeJS and Etherpad Archives
# -----------------------------------------------------
# Both of these are distributed as source archives. Since the names
# of both the archives as well as the directory trees they unpack to
# changes with the version along with the location to download from,
# this script assumes that you've downloaded both distributions and
# have placed them somewhere where the Ansible server can get to them.
#
# Those locations go in global_vars.yml, and the script uses some
# (hopefully) clever logic to figure out the names of the unpacked
# directory trees and rename them to something canonical.
#
  
- hosts: pangolin_server
  become: yes
  pre_tasks:
    - name: Get global variables before roles are run
      include_vars: global_vars.yml
  roles:
    - etherpad_server
  tasks:
    # Invoke Node for the first time to load all dependencies.
    - name: Run Node for the first time to load dependencies
      command:
        cmd: sudo -iu etherpad /home/etherpad/etherpad/bin/installDeps.sh
        chdir: /home/etherpad/etherpad
      become: no
    